---
# tasks file for nginx

- name: install tool 
  apt:
   name: "{{item}}"
   state: latest
  loop: "{{software}}"
  tags: ["install"]
    
- name: copy the configuration to nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{item.key}}
    mode: 0644
  with_dict: "{{sites}}"
  notify: restart nginx
  tags: ["configure"]
    
- name: get active site
  shell: ls -1 /etc/nginx/sites-enabled/
  register: active
  changed_when: "active.stdout_lines != sites.keys()"
  tags: ["configure"]

#- debug: 
#   var: sites["myapp"].frontend 

- name: deactivate the inactive site
  file: 
   path: /etc/nginx/sites-enabled/{{item}}
   state: absent
  loop: "{{active.stdout_lines}}"
  when: item not in sites
  notify: restart nginx
  tags: ["configure"]

- name: activate nginx site
  file:
   src: /etc/nginx/sites-available/{{item.key}}
   dest: /etc/nginx/sites-enabled/{{item.key}}
   state: link
  with_dict: "{{sites}}"
  notify: restart nginx
  tags: ["configure"]

- name: start the nginx service 
  service:
   name: nginx
   state: started
   enabled: yes 
  tags: ["service"]